### ISSUE TITLE
App Loader can't show file upload/download dialogs

### ISSUE THREAD

**Issue by gfwilliams** [gfwilliams/Gadgetbridge#6]
First reported at https://github.com/espruino/BangleApps/issues/2073

Basically we can't upload or download files because the file chooser isn't shown. The standard code for doing this seems to be:

```
webView.setDownloadListener(new DownloadListener() {
            public void onDownloadStart(String url, String userAgent,
                                        String contentDisposition, String mimetype,
                                        long contentLength) {
                DownloadManager.Request request = new DownloadManager.Request(Uri.parse(url)); //  fails with java.lang.IllegalArgumentException: Can not handle uri::
                request.allowScanningByMediaScanner();
                request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);
                request.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, "download");
                DownloadManager dm = (DownloadManager) getSystemService(DOWNLOAD_SERVICE);
                dm.enqueue(request);
            }
        });
```

But since we're now downloading a file but are instead downloading a blob - eg https://banglejs.com/614cd169-8d88-4b34-a57c-af34a162a03f - this fails with:

```
java.lang.IllegalArgumentException: Can not handle uri:: blob:https://banglejs.com/614cd169-8d88-4b34-a57c-af34a162a03f
        at android.app.DownloadManager$Request.checkUri(DownloadManager.java:779)
        at android.app.DownloadManager$Request.<init>(DownloadManager.java:762)
        at nodomain.freeyourgadget.gadgetbridge.devices.banglejs.AppsManagementActivity$3.onDownloadStart(AppsManagementActivity.java:185)
```

**Comment by Moini** [comment]
I ran into this issue, too, and didn't understand what was wrong. Thought it had to do with the specific file I was trying to download...

**Comment by gfwilliams** [comment]
I think this is actually fixed now anyway https://codeberg.org/Freeyourgadget/Gadgetbridge/commit/c647c2647f1b14369edaf5d4597f14c369ec0510

**Comment by Moini** [comment]
Nice, thanks for the heads up, @gfwilliams !
